// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj_AwjnodzchK_dHwcySULXM2BIOQL5uM',
    appId: '1:945753521233:web:c60f2390d680fe84044c70',
    messagingSenderId: '945753521233',
    projectId: 'quizon-5e627',
    authDomain: 'quizon-5e627.firebaseapp.com',
    storageBucket: 'quizon-5e627.firebasestorage.app',
    measurementId: 'G-1L6D6FBL41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCITfoYIdKu6HjL6EETTc4i1AbOYJnUDBA',
    appId: '1:945753521233:android:fdfb126ec99d3484044c70',
    messagingSenderId: '945753521233',
    projectId: 'quizon-5e627',
    storageBucket: 'quizon-5e627.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACiPwrl1gqMBSK3f_Z6CRS6v2yzLc8iBw',
    appId: '1:945753521233:ios:cf9d2ca68e866a97044c70',
    messagingSenderId: '945753521233',
    projectId: 'quizon-5e627',
    storageBucket: 'quizon-5e627.firebasestorage.app',
    iosBundleId: 'com.example.quizon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACiPwrl1gqMBSK3f_Z6CRS6v2yzLc8iBw',
    appId: '1:945753521233:ios:cf9d2ca68e866a97044c70',
    messagingSenderId: '945753521233',
    projectId: 'quizon-5e627',
    storageBucket: 'quizon-5e627.firebasestorage.app',
    iosBundleId: 'com.example.quizon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj_AwjnodzchK_dHwcySULXM2BIOQL5uM',
    appId: '1:945753521233:web:b3aa9d1df0e24948044c70',
    messagingSenderId: '945753521233',
    projectId: 'quizon-5e627',
    authDomain: 'quizon-5e627.firebaseapp.com',
    storageBucket: 'quizon-5e627.firebasestorage.app',
    measurementId: 'G-EHWYCC0Z14',
  );
}
